
spring:
  application:
    name: obervability-spring-grafana
  datasource:
    url: jdbc:postgresql://postgresql:5432/product-db
    username: admin
    password: admin


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    correlation: ${spring.application.name:},%X{traceId:-},%X{spanId:-}
