global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel'
    scrape_interval: 5s
    static_configs:
      - targets: ['product-service:8081']
        labels:
          application: 'Product Service Application'